version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672" 
      - "15672:15672"
      - "8024:61613"
    volumes:
      - ./rabbitmq-init.sh:/docker-entrypoint-initdb.d/rabbitmq-init.sh
    command: >
      bash -c "
        chmod +x /docker-entrypoint-initdb.d/rabbitmq-init.sh &&
        rabbitmq-plugins enable rabbitmq_stomp &&
        rabbitmq-plugins enable rabbitmq_web_stomp &&  # Add this line
        rabbitmq-plugins enable rabbitmq_management &&
        rabbitmq-server &
        sleep 20 &&
        /docker-entrypoint-initdb.d/rabbitmq-init.sh &&
        wait"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass abc123
    volumes:
      - redis-data:/data
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0:abc123
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
